name: appgui
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  #flutter packages
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  redux_epics: ^0.15.1

  #dart packages
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  owoify_dart: ^2.0.1
  injectable: ^2.1.0
  get_it: ^7.2.0
  envied: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3
  envied_generator: ^0.3.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/